<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class RelacionModulos extends CI_Controller{

  public function __construct()
  {
    parent::__construct();
    $this->load->model(array('sis/Menu'));
  }

  function index()
  {

  }
  public function datajstree(){
    $menus= $this->Menu->findBy(array('idmenuPadre'=>NULL));
    foreach ($menus as $key) {
        $key->getHijos();

    }
    echo json_encode($menus,JSON_PRETTY_PRINT);
    $json='{
            id          : "string" // will be autogenerated if omitted
            text        : "string" // node text
            icon        : "string" // string for custom
            state       : {
              opened    : boolean  // is the node open
              disabled  : boolean  // is the node disabled
              selected  : boolean  // is the node selected
            },
            children    : []  // array of strings or objects
            li_attr     : {}  // attributes for the generated LI node
            a_attr      : {}  // attributes for the generated A node
          }';
  }

}
